title: ML Wiki
email: alexey@datatalks.club
description: >- # this means to ignore newlines until "baseurl:"
  Machine Learning Wiki - A collection of ML concepts, algorithms, and resources.

github_repository: https://github.com/alexeygrigorev/mlwiki.org

exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - data/
  - .venv/
  - pyproject.toml
  - uv.lock
  - transfer.py
