[project]
name = "mlwiki-org"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "lxml>=6.0.1",
    "markdownify>=1.2.0",
    "mwparserfromhell>=0.7.2",
    "pygments>=2.19.2",
]
